# Generated by Django 5.1.6 on 2025-03-25 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coapp', '0003_rename_answer1_1_test_answer_option1_1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='test_grade_1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='test_grade_2',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='test_grade_3',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='test_grade_4',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='test_grade_5',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='test_grade_6',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='adress',
            field=models.CharField(blank=True, max_length=100, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Аккаунт активен'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Аккаунт проверен'),
        ),
        migrations.CreateModel(
            name='CourseGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_grade_1', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Оценка за первый блок')),
                ('test_grade_2', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Оценка за второй блок')),
                ('test_grade_3', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Оценка за третий блок')),
                ('test_grade_4', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Оценка за четвертый блок')),
                ('test_grade_5', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Оценка за пятый блок')),
                ('test_grade_6', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Оценка за шестой блок')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='coapp.course', verbose_name='Курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_grades', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оценки за курс',
                'verbose_name_plural': 'Оценки за курсы',
            },
        ),
    ]
