# Generated by Django 5.1.6 on 2025-03-28 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coapp', '0004_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseexercise',
            options={'verbose_name': 'Материалы для курса', 'verbose_name_plural': 'Материалы для курса'},
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coapp.category', verbose_name='Направление статьи'),
        ),
        migrations.AlterField(
            model_name='course',
            name='termsofstudy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coapp.term_of_study', verbose_name='Срок обучения'),
        ),
        migrations.AlterField(
            model_name='course',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coapp.topic', verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='courseexercise',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coapp.course', verbose_name='Курс к которому принадлежит документ'),
        ),
    ]
