# Generated by Django 5.1.6 on 2025-03-28 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coapp', '0005_alter_courseexercise_options_alter_course_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coapp.course', verbose_name='Курс к которому принадлежит тест'),
        ),
    ]
