# Generated by Django 5.1.6 on 2025-03-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coapp', '0006_alter_test_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='scans_approved',
            field=models.BooleanField(default=False, verbose_name='Сканы документов проверены'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
