# Generated by Django 5.1.6 on 2025-03-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coapp', '0007_customuser_scans_approved_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='picture1',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Диплом о высшем или среднем образовании (JPG/JPEG/PNG)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Документ о смене фамилии (JPG/JPEG/PNG)'),
        ),
    ]
