# Generated by Django 5.1.6 on 2025-03-30 20:30

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coapp', '0008_alter_customuser_picture1_alter_customuser_picture2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Личный кабинет', 'verbose_name_plural': 'Личный кабинет'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='education',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='paid_courses',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='picture1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='picture2',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='promocode',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='scans_approved',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='snils',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.CreateModel(
            name='UserReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Полные ФИО обучаемого')),
                ('phone_number', models.CharField(blank=True, max_length=100, verbose_name='Номер телефона')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Адрес доставки')),
                ('birthdate', models.DateField(null=True, verbose_name='Дата вашего рождения')),
                ('snils', models.CharField(blank=True, max_length=100, verbose_name='СНИЛС(11 чисел)')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Мужчина'), ('female', 'Женщина')], max_length=6, null=True, verbose_name='Пол')),
                ('promocode', models.CharField(blank=True, max_length=100, verbose_name='Промокод')),
                ('education', models.CharField(blank=True, choices=[('среднее профессиональное образование', 'Среднее профессиональное образование'), ('высшее образование', 'Высшее образование')], max_length=100, null=True, verbose_name='Образование')),
                ('picture1', models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Диплом о высшем или среднем образовании (JPG/JPEG/PNG)')),
                ('picture2', models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Документ о смене фамилии (JPG/JPEG/PNG)')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Аккаунт проверен')),
                ('scans_approved', models.BooleanField(default=False, verbose_name='Сканы документов проверены')),
                ('courses', models.ManyToManyField(blank=True, related_name='purchased_by', to='coapp.course', verbose_name='Курсы')),
                ('paid_courses', models.ManyToManyField(blank=True, related_name='paid_by_users', to='coapp.course', verbose_name='Оплаченные курсы')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль к курсу',
                'verbose_name_plural': 'Профиль к курсу',
            },
        ),
    ]
