# Generated by Django 5.1.6 on 2025-03-31 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coapp', '0009_alter_customuser_options_remove_customuser_adress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreg',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
