# Generated by Django 5.1.6 on 2025-03-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coapp', '0010_alter_userreg_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreg',
            name='username',
            field=models.CharField(max_length=50, verbose_name='Полные ФИО обучаемого'),
        ),
    ]
