# Generated by Django 5.1.6 on 2025-03-31 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coapp', '0011_alter_userreg_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreg',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='userreg',
            name='paid_courses',
        ),
        migrations.AddField(
            model_name='userreg',
            name='course',
            field=models.ForeignKey(blank=True, default=6, on_delete=django.db.models.deletion.CASCADE, related_name='purchased_by', to='coapp.course', verbose_name='Курс'),
            preserve_default=False,
        ),
    ]
