# Generated by Django 5.1.6 on 2025-04-05 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coapp', '0012_remove_userreg_courses_remove_userreg_paid_courses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
        migrations.AlterField(
            model_name='userreg',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер телефона или адрес электронной почты'),
        ),
        migrations.CreateModel(
            name='CourseTimeToBeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=100, verbose_name='Срок')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coapp.course', verbose_name='Курс к которому принадлежит документ')),
            ],
            options={
                'verbose_name': 'Сроки для курса',
                'verbose_name_plural': 'Сроки для курса',
            },
        ),
    ]
