# Generated by Django 5.1.6 on 2025-04-05 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coapp', '0013_remove_course_price_alter_userreg_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetimetobeat',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coapp.term_of_study', verbose_name='Срок'),
        ),
    ]
