# Generated by Django 5.1.6 on 2025-04-05 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coapp', '0014_alter_coursetimetobeat_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='termsofstudy',
        ),
    ]
