# Generated by Django 5.1.6 on 2025-04-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coapp', '0015_remove_course_termsofstudy'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Курс оплачен'),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='education',
            field=models.CharField(blank=True, choices=[('basic', 'Основное общее (5-9 классы)'), ('secondary', 'Среднее общее (10-11 классы)'), ('specialized', 'Среднее специальное образование'), ('higher', 'Высшее образование')], max_length=12, null=True, verbose_name='Уровень образования'),
        ),
    ]
