# Generated by Django 5.1.6 on 2025-04-06 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coapp', '0016_userreg_is_paid_alter_userreg_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='time_to_beat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coapp.coursetimetobeat', verbose_name='Срок курса'),
        ),
    ]
