# Generated by Django 5.1.6 on 2025-04-10 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coapp', '0017_userreg_time_to_beat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'фильтрация:  Направление', 'verbose_name_plural': 'фильтрация:  Направление'},
        ),
        migrations.AddField(
            model_name='userreg',
            name='is_sended',
            field=models.BooleanField(default=False, verbose_name='Отправили почтой диплом'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coapp.category', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='course',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coapp.topic', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Введенные при регистрации данные проверены'),
        ),
    ]
