# Generated by Django 5.1.6 on 2025-04-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coapp', '0018_alter_topic_options_userreg_is_sended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='blocks',
            field=models.PositiveIntegerField(default=1, verbose_name='Сколько блоков с материалами будет в этом курсе'),
            preserve_default=False,
        ),
    ]
