# Generated by Django 5.1.6 on 2025-04-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coapp', '0019_course_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='recieved_docs',
            field=models.BooleanField(default=False, verbose_name='Получил диплом'),
        ),
    ]
