# Generated by Django 5.1.6 on 2025-04-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coapp', '0020_userreg_recieved_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='attestation_finished',
            field=models.BooleanField(default=False, verbose_name='Аттестация пройдена'),
        ),
    ]
