# Generated by Django 5.1.6 on 2025-04-26 23:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coapp', '0021_userreg_attestation_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='date_end',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата завершения'),
        ),
    ]
