# Generated by Django 5.1.6 on 2025-04-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coapp', '0022_userreg_date_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreg',
            name='date_end',
            field=models.DateTimeField(verbose_name='Дата завершения'),
        ),
    ]
