# Generated by Django 5.1.6 on 2025-04-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coapp', '0023_alter_userreg_date_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetimetobeat',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Срок в часах'),
        ),
    ]
