# Generated by Django 5.1.6 on 2025-04-27 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coapp', '0024_coursetimetobeat_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursetimetobeat',
            name='duration',
        ),
    ]
