# Generated by Django 5.1.6 on 2025-04-27 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coapp', '0025_remove_coursetimetobeat_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreg',
            name='date_end',
        ),
    ]
