# Generated by Django 5.1.6 on 2025-04-27 22:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coapp', '0026_remove_userreg_date_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата завершения'),
        ),
    ]
