# Generated by Django 5.1.6 on 2025-04-27 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coapp', '0027_userreg_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreg',
            name='end_date',
            field=models.DateTimeField(verbose_name='Дата завершения'),
        ),
    ]
