# Generated by Django 5.1.6 on 2025-06-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coapp', '0028_alter_userreg_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pdf_1',
            field=models.FileField(blank=True, null=True, upload_to='course_pdfs/', verbose_name='Файл (Формат PDF)'),
        ),
        migrations.AddField(
            model_name='course',
            name='pdf_2',
            field=models.FileField(blank=True, null=True, upload_to='course_pdfs/', verbose_name='Файл (Формат PDF)'),
        ),
        migrations.AddField(
            model_name='course',
            name='pdf_3',
            field=models.FileField(blank=True, null=True, upload_to='course_pdfs/', verbose_name='Файл (Формат PDF)'),
        ),
    ]
