# Generated by Django 5.1.6 on 2025-06-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coapp', '0029_course_pdf_1_course_pdf_2_course_pdf_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pdf_1',
            field=models.FileField(blank=True, null=True, upload_to='course_pdfs/', verbose_name='договор (Формат PDF)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='pdf_2',
            field=models.FileField(blank=True, null=True, upload_to='course_pdfs/', verbose_name='учебный план (Формат PDF)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='pdf_3',
            field=models.FileField(blank=True, null=True, upload_to='course_pdfs/', verbose_name='программа обучения (Формат PDF)'),
        ),
    ]
