# Generated by Django 5.1.6 on 2025-07-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coapp', '0032_alter_test_options_remove_test_answer_option1_1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answeroption',
            options={'ordering': ['position'], 'verbose_name': 'Вариант ответа', 'verbose_name_plural': 'Варианты ответов'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['position'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AddField(
            model_name='answeroption',
            name='position',
            field=models.PositiveIntegerField(default=1, verbose_name='Номер варианта'),
        ),
        migrations.AddField(
            model_name='question',
            name='position',
            field=models.PositiveIntegerField(default=1, verbose_name='Номер вопроса'),
        ),
    ]
