# Generated by Django 5.1.6 on 2025-07-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coapp', '0033_alter_answeroption_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answeroption',
            options={'verbose_name': 'Тесты: Вариант ответа', 'verbose_name_plural': 'Тесты: Варианты ответов'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Тесты: Вопрос', 'verbose_name_plural': 'Тесты: Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'свТест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.AddField(
            model_name='test',
            name='questions_number',
            field=models.PositiveIntegerField(null=True, verbose_name='Количество вопросов'),
        ),
    ]
