# Generated by Django 5.1.6 on 2025-07-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coapp', '0034_alter_answeroption_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_1correct',
            field=models.BooleanField(default=False, verbose_name='Правильный ответ'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_2correct',
            field=models.BooleanField(default=False, verbose_name='Правильный ответ'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_3correct',
            field=models.BooleanField(default=False, verbose_name='Правильный ответ'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_4correct',
            field=models.BooleanField(default=False, verbose_name='Правильный ответ'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_1',
            field=models.CharField(default='Ответ 1', max_length=200, verbose_name='Вариант ответа'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_2',
            field=models.CharField(default='Ответ 2', max_length=200, verbose_name='Вариант ответа'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_3',
            field=models.CharField(default='Ответ 3', max_length=200, verbose_name='Вариант ответа'),
        ),
        migrations.AddField(
            model_name='question',
            name='text_4',
            field=models.CharField(default='Ответ 2', max_length=200, verbose_name='Вариант ответа'),
        ),
    ]
