# Generated by Django 5.1.6 on 2025-07-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coapp', '0035_question_is_1correct_question_is_2correct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text_4',
            field=models.CharField(default='Ответ 4', max_length=200, verbose_name='Вариант ответа'),
        ),
    ]
