# Generated by Django 5.1.6 on 2025-07-13 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coapp', '0036_alter_question_text_4'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnswerOption',
        ),
    ]
