# Generated by Django 5.1.6 on 2025-07-14 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coapp', '0037_delete_answeroption'),
    ]

    operations = [
        migrations.AddField(
            model_name='term_of_study',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(days=5), verbose_name='Продолжительность обучения'),
        ),
    ]
