# Generated by Django 5.1.6 on 2025-07-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coapp', '0038_term_of_study_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term_of_study',
            name='slug',
        ),
        migrations.AlterField(
            model_name='term_of_study',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название для вывода на главной странице'),
        ),
    ]
