# Generated by Django 5.1.6 on 2025-07-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coapp', '0039_remove_term_of_study_slug_alter_term_of_study_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
    ]
