# Generated by Django 5.1.6 on 2025-07-21 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coapp', '0040_paymentlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlog',
            name='user_reg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coapp.userreg'),
        ),
    ]
