# Generated by Django 5.1.6 on 2025-08-29 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coapp', '0041_paymentlog_user_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название промокода вот')),
                ('percent', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Процент скидки промокода')),
                ('expires_at', models.DateTimeField(verbose_name='Время окончания промокода')),
            ],
        ),
        migrations.AlterField(
            model_name='userreg',
            name='promocode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Промокод'),
        ),
    ]
