# Generated by Django 5.1.6 on 2025-08-29 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coapp', '0042_promocode_alter_userreg_promocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreg',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='coapp.promocode', verbose_name='Промокод'),
        ),
    ]
